version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: librarymanager-db
    restart: always
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: libraryuser
      POSTGRES_PASSWORD: librarypass
      TZ: America/Bogota
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: librarymanager-api
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/librarydb
      SPRING_DATASOURCE_USERNAME: libraryuser
      SPRING_DATASOURCE_PASSWORD: librarypass
      SERVER_PORT: 8080
      TZ: America/Bogota
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data:
